export enum TransactionType {
    EXTERNAL_TRANSFER='OUTWARD TRANSFER',
    INTERNAL_TRANSFER='INTERNAL TRANSFER',
    CARD_WITHDRAWAL='CARD WITHDRAWAL',
    CARD_CREATION='CARD_CREATION',
    INVESTMENT_WITHDRAWAL='INVESTMENT WITHDRAWAL',
    INVESTMENT_FUNDING='INVESTMENT FUNDING',
    BANK_FUNDING='BANK_FUNDING',
    INVOICE_PAYMENT = 'INVOICE_PAYMENT'
}

export enum TransactionStatus {
    SUCCESS='Success',
    PENDING='Pending',
    FAILED='Failed'
}